### ISSUE TITLE
Widgetkit Plugin does not work

### ISSUE THREAD

**Issue by JamborJan** [dwrensha/wordpress-sandstorm#1]
Hi,

I have an "Critical Issues: No GD library available." in WordPress. I have themes and plugins from http://yootheme.com and they have the requirement to have the web server running with the GD library enabled.

Can this be changed or are there any concerns doing this?

Thanks
JJ

**Comment by JamborJan** [comment]
Hey @dwrensha I know you guys are pretty busy these days, wanted to ask if it is rather likely or not that a solution like union file system will be introduced or not.

I would love to move some pages to sandstorm but at the moment most of them use themes and the widgetkit from those guys: http://yootheme.com/

If I can help with this let me know.

JJ

**Comment by dwrensha** [comment]
Unfortunately, I still haven't determined the best path forward here. I think Sandstorm is unlikely to support a union/overlay filesystem (at least any time soon). Another strategy we might take here could be to implement in Sandstorm a notion of "app add-on" so that WordPress plugins could be installed as sub-packages of the main WordPress spk. With this approach, plugins would get installed in read-only app storage without any symlink indirection and we wouldn't see any of the path normalization problems we were seeing above. However, the problem with this approach for WordPress plugins is that they often expect to be able to write to their install directory. E.g. the WidgetKit plugin wants to write to its /cache directory. So to get that to work, it seems that we need to allow add-ons to specify "bind-mounts" into grain storage. So it starts to get complicated.

Hmm. Maybe the best course of action for us right now would be to gather an understanding of what other apps might expect in a notion of "app add-on". If that matches up with what we need here, then perhaps the added complication is justified.

**Comment by JamborJan** [comment]
Thanks for sharing your thoughts on this topic. It is for sure the best idea to identify a use case which applies to other apps too and to find a proper solution based on that. Sorry when I write the same thing again here with my own words, it helps me understanding the issue and maybe get a better idea of it.

From my point of view the use case seems to be at the moment more or less like that:
- App with a defined limited set of features
- Possibility to add features with plugins
- Plugins want to save data (cache, user data)
- Plugins use own methods to determine paths

Behavior today:
- Plugins are installed in writable /var folder (symlinked)
- Issue: Plugins determine paths with functions which cannot handle symlinks properly
- Issue: Plugins determine paths by assuming hard coded defaults and adding / removing hard coded elements of the path

Alternative:
- Install Plugins not via app itself but via a seperate sub-package
- When installing it as a sub-package (which needs to be invented first in the sandstorm universe) the plugin would find itself in the expected folder (not symlinked) hard coded paths and other functions would work
- Problem: every single plugin needs to be packaged in a separate package with own symlink to /var if they want to write data
- Problem: this might cause a recursion of the issue to a component of the plugin
- After all: this seems not suitable from my point of view

So basically what I see here between the lines: if the actual app vendor would use proper functions to determine paths (nothing hard coded and all symlink friendly) then the issue would not occur. So a real solution is to help the vendor / upstream maintainer fix the issue. But as companies like yootheme might not consider doing this we might get stuck here.

I have no idea what an alternative solution can be, therefor I have too little detailed knowledge of what is really possible and what is simply magic and fairy tales. One of these magic options would be detecting when an app/package is trying to use a function or hard coded paths which is known for delivering a wrong current path when symlinked and replace it / fake the result with the actual path. If something like this would be possible it must be handled in the package of the "mother app" of the plugin. So when the plugin tries to figure out a path the app says "take this: /var/ ...".

Apps which might have this issue:
- Wordpress
- (maybe joomla or other CMS in the future)
- don't know, everything which can be enhanced by plugins

JJ

**Comment by xet7** [comment]
This issue was moved to wpsandstorm/wordpress-sandstorm#1
