### ISSUE TITLE
Sending emails from wordpress

### ISSUE THREAD

**Issue by JamborJan** [dwrensha/wordpress-sandstorm#12]
To make use of a contact form it would be required that the sandstorm port of wordpress is able to send emails. I know that this will be one of the drivers being available later.

It would be   cool that smtp connections would be allowed e.g. with this plugin:  https://downloads.wordpress.org/plugin/easy-wp-smtp.zip

With the mentioned extension I have the following problem:
- To use TLS OpenSSL would be required, when setting up the extension to use it an error message is shown

![bildschirmfoto 2015-10-31 um 15 42 44](https://cloud.githubusercontent.com/assets/7508960/10864195/10b45a70-7fe6-11e5-96b4-8d73f3d2045b.png)
- when using plain text email I get the error message `SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

![bildschirmfoto 2015-10-31 um 15 43 44](https://cloud.githubusercontent.com/assets/7508960/10864196/3a55eed4-7fe6-11e5-8213-ff68d724e73e.png)

As I'm not quite sure how the sandstorm port of wordpress is build I don't know which of the solutions posted here https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting might work.

Is there any plan of allowing to send emails by wordpress e.g. for contact forms?

Thanks!

**Comment by meitar** [comment]
Ahh, this seems similar to sandstorm-io/sandstorm#1902. In fact, maybe this tracker is the appropriate place for that other issue.

**Comment by dwrensha** [comment]
Hi! I think it would be possible to get this to work the same way that [the RoundCube app](https://github.com/jparyani/roundcubemail) works: by using the ["sandstorm SMTP bridge"](https://github.com/jparyani/sandstorm-smtp-bridge), which in turn uses [`HackEmailSession`]( https://github.com/sandstorm-io/sandstorm/blob/v0.160/src/sandstorm/hack-session.capnp#L99). To get WordPress to talk to the SMTP bridge we would need to make sure that [`php.ini`](https://github.com/dwrensha/wordpress-sandstorm/blob/bd1b6fa1d03e95d0aea28e0b9a5e6152ef1116c1/etc/php/php.ini#L989-L1016) has appropriate configuration.

So far, I've been hesitant to hook this up until we have proper powerbox support, so that the user would have the option of denying the email-sending capability.

**Comment by meitar** [comment]
@dwrensha Can you elaborate on "powerbox support"? (Or link me to an explanation?) I'd be willing to look into this myself because lack of emails from WordPress are a showstopper for my use case.

Thanks again!

**Comment by dwrensha** [comment]
There's some explanation about the powerbox [here](https://sandstorm.io/how-it-works#powerbox).

**Comment by xet7** [comment]
This issue was moved to wpsandstorm/wordpress-sandstorm#8
